Sources/BugsnagPerformance/Private/BSGInternalConfig.c, Sources/BugsnagPerformance/Private/BSGInternalConfig.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/Sampler.h, Sources/BugsnagPerformance/Private/Sampler.mm, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/ProbabilityExpiryScenario.swift, features/initial-p-value.feature
When the current P value expires, start fetching P values from the server on span start instead of reverting to the original configured value.
Also added a delay latch so that it can't send P value requests more than once every 30 seconds (so that we don't flood the server on span-heavy apps whenever the timer expires).
New e2e scenario to test p value expiry.
=> [PLAT-9461] Don't revert to the configured P value on expiry.

Sources/BugsnagPerformance/Private/OtlpTraceEncoding.mm, Tests/BugsnagPerformanceTests/OtlpTraceEncodingTests.mm, features/automatic_spans.feature, features/initial-p-value.feature, features/manual_spans.feature, features/steps/app_steps.rb
Use integer values for enum fields instead of string values.
Updated tests to check for integer values.
=> [PLAT-9677] Use integer values for enums instead of strings

BugsnagPerformance.xcodeproj/project.pbxproj, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceSpanOptions+Private.h, Sources/BugsnagPerformance/Private/SpanData.h, Sources/BugsnagPerformance/Private/SpanData.mm, Sources/BugsnagPerformance/Private/SpanOptions.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpanOptions.m, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanOptions.h, Tests/BugsnagPerformanceTests/BatchTests.mm, Tests/BugsnagPerformanceTests/OtlpTraceEncodingTests.mm, Tests/BugsnagPerformanceTests/SamplerTests.mm, Tests/BugsnagPerformanceTests/SpanContextStackTests.mm, Tests/BugsnagPerformanceTests/SpanOptionsTests.mm, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/FirstClassNoScenario.swift, features/fixtures/ios/Scenarios/FirstClassYesScenario.swift, features/manual_spans.feature, features/steps/app_steps.rb
This PR adds support for the `bugsnag.span.first_class` span attribute.
Replaced the `BSGFirstClass` enum with two booleans `isFirstClass` and `wasFirstClassSet` because Swift wasn't happy with the enum. `wasFirstClassSet` is internally accessible only.
Special processing of unset `isFirstClass` values is being done in the SpanOptions header for now. The defaults for views will likely be moved to a different file when support for traversing view hierarchies is added later.
Added e2e and unit tests.
=> [Plat 9654] first class spans

Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Public/BugsnagPerformance.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceConfiguration.mm, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformance.h, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceConfiguration.h, Tests/BugsnagPerformanceTests/BugsnagPerformanceConfigurationTests.mm, Tests/BugsnagPerformanceTests/BugsnagPerformanceTests.mm, Tests/BugsnagPerformanceTests/ResourceAttributesTests.mm, Tests/BugsnagPerformanceTestsSwift/ConfigurationTests.swift, features/fixtures/ios/Scenarios/Scenario.swift
Simplify BugsnagPerformance.start API
Since there’s only one user-controllable thing that can go wrong when BugsnagPerformance starts, we don’t really need the complication of declared Swift errors and return status values.
Unit Tests
=> [PLAT-9798] Simplified BugsnagPerformance.start API

Example/Example.xcodeproj/project.pbxproj, Example/Example/Base.lproj/Main.storyboard, Example/Example/ViewController.swift, Sources/BugsnagPerformance/Private/SpanAttributes.mm, features/manual_spans.feature
* Disabled app foreground check for now because it has the potential to hang the main thread.
* Temporarily removed example library from the example app because it was causing dynamic linker issues.
* Moved `AnotherViewController` to the main app.
* Disabled the SwiftUI button for now (fix incoming).
=> Disable in fg check

CHANGELOG.md, Example/Example/Base.lproj/Main.storyboard
* Reverted the swiftui button removal
* Add more detail to the example app buttons about what to expect:
- "SwiftUI View (manual)"
- "UIViewController (ignored)"
=> Final fixes

Gemfile, Gemfile.lock, Sources/BugsnagPerformance/Private/AppStateTracker.h, Sources/BugsnagPerformance/Private/AppStateTracker.m, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/SpanAttributes.mm, features/fixtures/ios/Scenarios/BackgroundForegroundScenario.swift, features/manual_spans.feature, features/steps/app_steps.rb, features/triggers.feature
The old background status check dispatched to the main queue and waited, but if the code that calls `BugsnagPerformanc.start` waits on the main thread, we deadlock.
The new design uses `NSNotificationCenter` as well as a check at the earliest point in the Objective-C runtime initialization so that this can be avoided.
`AppStateTracker` now keeps a boolean value containing the latest updated app background state in addition to its existing callback responsibility.
The initial state is grabbed during `initialize` so that it must run on the main thread. After that, all updates are done via `NSNotificationCenter`.
Re-enabled and enhanced app background state tests.
=> [PLAT-9823] Re-enable background/foreground status check

Sources/BugsnagPerformance/Private/BSGInternalConfig.h
Some clients are getting compile time errors because our code is importing `dispatch/time.h`.
Import `dispatch/dispatch.h` instead, as per the error message.
=> Import main dispatch header rather than dispatch/time.h

.swiftpm/xcode/xcshareddata/xcschemes/BugsnagPerformance.xcscheme, Example/Example.xcodeproj/project.pbxproj, Example/Example.xcodeproj/xcshareddata/xcschemes/Example.xcscheme, Example/Example/Example-Bridging-Header.h, Example/Example/ForceUBSan.h, Example/Example/ForceUBSan.m, Sources/BugsnagPerformance/Private/Batch.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.h, Sources/BugsnagPerformance/Private/OtlpPackage.h, Sources/BugsnagPerformance/Private/OtlpUploader.h, Sources/BugsnagPerformance/Private/Persistence.h, Sources/BugsnagPerformance/Private/PersistentState.h, Sources/BugsnagPerformance/Private/ResourceAttributes.h, Sources/BugsnagPerformance/Private/RetryQueue.h, Sources/BugsnagPerformance/Private/Sampler.h, Sources/BugsnagPerformance/Private/Span.h, Sources/BugsnagPerformance/Private/SpanData.h, Sources/BugsnagPerformance/Private/SpanOptions.h, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Version.h, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Fixture.xcodeproj/xcshareddata/xcschemes/Fixture.xcscheme, features/fixtures/ios/Scenarios/ForceUBSan.h, features/fixtures/ios/Scenarios/ForceUBSan.m
Some of the C++ objects weren't initializing their members, resulting in undefined behaviour.
This PR adds default initializers to all C++ members that are not `std::something` (those types have default initializers already).
The example app and maze runner fixture have also been modified to turn on every sanitizer possible.
=> [PLAT-9830] Enable UBSan and malloc scribble on the example app and the maze runner app

BugsnagPerformance.xcodeproj/project.pbxproj, Gemfile, Gemfile.lock, Sources/BugsnagPerformance/Private/AppStateTracker.m, Sources/BugsnagPerformance/Private/Targets.h
Using `#if __has_include(<AppKit/AppKit.h>)` breaks on mac catalyst targets because they do have an appkit include that lacks most of appkit.
* Use the `TARGET_OS_xyz` defines as a base instead.
* Build new conditionals that target technologies rather than platforms.
* Put the checks in a centralized `Targets.h` to avoid future copypasta bugs.
=> Fix compile issue with mac catalyst targets

Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.mm, Sources/BugsnagPerformance/Private/SpanData.h, Sources/BugsnagPerformance/Private/SpanData.mm, Sources/BugsnagPerformance/Private/SpanOptions.h, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpanOptions.m, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanOptions.h, Tests/BugsnagPerformanceTests/BatchTests.mm, Tests/BugsnagPerformanceTests/OtlpTraceEncodingTests.mm, Tests/BugsnagPerformanceTests/SamplerTests.mm, Tests/BugsnagPerformanceTests/SpanContextStackTests.mm, Tests/BugsnagPerformanceTests/SpanOptionsTests.mm, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/FirstClassNoScenario.swift, features/fixtures/ios/Scenarios/FirstClassYesScenario.swift, features/manual_spans.feature, features/steps/app_steps.rb
Re-implementation of https://github.com/bugsnag/bugsnag-cocoa-performance/pull/56 to handle drift on `next`.
=> [Plat 9654] Add full support for the first_class span attribute

Sources/BugsnagPerformance/Private/Sampler.mm
Update the comparison to match the spec (it should be comparing less than or equal).
=> [PLAT-9907] Sampling comparison should be <=, not <

Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm
Logging that each trace would not be sent was causing too much spam. Report only once at startup instead.
=> Only log once that reporting is disabled due to release stage

Sources/BugsnagPerformance/Private/Batch.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceSpan+Private.h, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, Sources/BugsnagPerformance/Private/OtlpTraceEncoding.h, Sources/BugsnagPerformance/Private/OtlpTraceEncoding.mm, Sources/BugsnagPerformance/Private/Sampler.h, Sources/BugsnagPerformance/Private/Sampler.mm, Sources/BugsnagPerformance/Private/Span.h, Sources/BugsnagPerformance/Private/SpanContextStack.h, Sources/BugsnagPerformance/Private/SpanContextStack.mm, Sources/BugsnagPerformance/Private/SpanData.h, Sources/BugsnagPerformance/Private/SpanData.mm, Sources/BugsnagPerformance/Private/SpanOptions.h, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm, Tests/BugsnagPerformanceTests/BatchTests.mm, Tests/BugsnagPerformanceTests/OtlpTraceEncodingTests.mm, Tests/BugsnagPerformanceTests/SpanContextStackTests.mm, features/automatic_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Fixture/Fixture.swift, features/fixtures/ios/Scenarios/AutoInstrumentSubViewLoadScenario.swift, features/fixtures/ios/Scenarios/Scenario.swift, features/steps/app_steps.rb
When the `first_class` span option is unset for a view controller, set it to `false` if there's any existing view span in the current hierarchy, otherwise set it to `true`.
We used to only use the C++ `Span` object from `Tracer` onwards for speed purposes, but it must now add the user-facing `BugsnagPerformanceSpan` to the current context stack based on the `makeContextCurrent` option, so `Tracer` is now aware of the ObjC class. This is only slightly heavier, however, since the rest of the span management is still done using the faster C++ objects.
We use an `NSPointerArray` in the context stack because it supports weak references.
`std::unique_ptr` unfortunately doesn't play nice with atomics, so I've had to change the `SpanData` pointers to use `std::shared_ptr` instead.
I've also added …
=> [PLAT-9655] Set view span first_class based on whether other view spans are active

Sources/BugsnagPerformance/Private/Batch.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceLibrary.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceLibrary.mm, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, Tests/BugsnagPerformanceTests/BugsnagPerformanceTests.mm, Tests/BugsnagPerformanceTests/ViewControllerSpanTests.mm
**Note**: Review after https://github.com/bugsnag/bugsnag-cocoa-performance/pull/94 has been merged.
It's possible for `viewDidAppear` to not be called in some circumstances. As a fallback, use `viewWillDisappear` to end the view load span.
The library has been tweaked to allow starting and shutting down the entire library from within the unit testing framework. This allows more complex interactions such as method swizzling to be tested at the unit test level.
Added unit tests for auto view load instrumentation.
=> [PLAT-9658] Handle possibility that viewDidAppear doesn't get called

Sources/BugsnagPerformance/Private/AppStateTracker.h, Sources/BugsnagPerformance/Private/AppStateTracker.m, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceLibrary.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceLibrary.mm, Sources/BugsnagPerformance/Private/SpanAttributes.mm, Tests/BugsnagPerformanceTests/SamplerTests.mm, Tests/BugsnagPerformanceTests/ViewControllerSpanTests.mm
The last PR only focused on C++ objects. This PR moves Objective-C globals into `BugsnagPerformanceLibrary`.
I've limited one one of the probability tests to ios 12+. On ios 11, the random number generator is biased so much that this probabilistic test fails (it should in theory only fail one in a million tests if the RNG is relatively unbiased).
The two testAutoViewController tests have been merged into one because resetting the library can cause memory corruption for some reason. The reset functionality was only meant for unit tests, so I'm leaving things as-is for now.
No functionality has changed (only where and when globals are initialized), so existing tests are sufficient.
=> Move AppStateTracker lifetime into BugsnagPerformanceLibrary

Sources/BugsnagPerformance/Private/Batch.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceConfiguration+Private.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceLibrary.mm, Sources/BugsnagPerformance/Private/Persistence.h, Sources/BugsnagPerformance/Private/Persistence.mm, Sources/BugsnagPerformance/Private/PersistentState.h, Sources/BugsnagPerformance/Private/PersistentState.mm, Sources/BugsnagPerformance/Private/RetryQueue.h, Sources/BugsnagPerformance/Private/RetryQueue.mm, Sources/BugsnagPerformance/Private/Sampler.h, Sources/BugsnagPerformance/Private/Sampler.mm, Sources/BugsnagPerformance/Private/Tracer.mm, Tests/BugsnagPerformanceTests/PersistenceTests.mm, Tests/BugsnagPerformanceTests/RetryQueueTests.mm, Tests/BugsnagPerformanceTests/SamplerTests.mm, features/fixtures/ios/Fixture/Fixture.swift, features/fixtures/ios/Scenarios/Scenario.swift
Some design issues were still present after the last PR:
* Some classes hadn't been changed over to the construct-config-start approach.
* `Persistence` was clearing on every run instead of just making sure the TLD exists.
* `Sampler` no longer maintains its own persistence.
* `Tracer` now drains the initial batch (which until configuration samples at 1.0) and re-adds them at the current sampling probability.
Also reverted `Batch` changes that allowed a null span.
Updated existing tests.
=> Construct-config-start conversion part 2

BugsnagPerformance.xcodeproj/project.pbxproj, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation/NSURLSession+Instrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, Sources/BugsnagPerformance/Private/Swizzle.h, Sources/BugsnagPerformance/Private/Swizzle.mm
There's a mix of swizzling code in some of the auto-instrumentation classes. This PR moves the fundamental operations to a centralized `ObjCSwizzle` class as static methods to namespace them and make it easier to find where swizzling is used in the project.
This is important for prospective users who are wary of swizzling so that they can have confidence that Bugsnag won't swizzle their code unless the features that require it are enabled in the configuration.
No new tests necessary since this is just moving code around.
=> Move all swizzle code to a single class to better understand where swizzling is used

Sources/BugsnagPerformance/Private/OtlpTraceEncoding.mm, Tests/BugsnagPerformanceTests/OtlpTraceEncodingTests.mm
Numeric values must always be encoded as strings in JSON.
Updated `OtlpTraceEncoding.mm` to always encode numbers as strings.
=> Ensure numeric values are always encoded as strings

Tests/BugsnagPerformanceTests/RetryQueueTests.mm
The RetryQueue unit tests weren't configuring the object before using it.
=> Ensure RetryQueue is configured when running tests

Sources/BugsnagPerformance/Private/OtlpTraceEncoding.mm, Tests/BugsnagPerformanceTests/OtlpTraceEncodingTests.mm
Double values should not be converted to strings when encoding JSON (only integers).
=> [PLAT-10056] Don't convert double values to strings when encoding JSON

BugsnagPerformance.xcodeproj/project.pbxproj, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceLibrary.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceLibrary.mm, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/Instrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/Instrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation/NSURLSession+Instrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, Sources/BugsnagPerformance/Private/Startable.h, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformance.mm, Tests/BugsnagPerformanceTests/ViewControllerSpanTests.mm
This PR moves management of the various instrumentation classes into a new `Instrumentation` class, which is owned by `BugsnagPerformanceLibrary`.
* Instrumentation classes are now `Configurable` and `Startable`, and follow the construct-configure-start pattern.
* `Tracer` instance is now a shared pointer.
These changes are necessary to support upcoming changes to record network spans across their durations rather than as a span recorded at the end (which is prone to incorrect span parentage).
No fundamental change in functionality, so existing tests must pass.
=> Move instrumentation management into Instrumentation class

Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceLibrary.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceLibrary.mm, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/Instrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.h, Sources/BugsnagPerformance/Private/Reachability.h, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm
Part 2 preparing for better network span support (part 1 here: https://github.com/bugsnag/bugsnag-cocoa-performance/pull/116)
* Removed some deep accesses (`object.subobject.subsubobject` and the like) and replaced them with forwarder functions.
* Some existing forwarder functions and roundabout access were unnecessary after refactoring.
* The code in `BugsnagPerformanceImpl::reportNetworkSpan` is duplicated for now, but one copy will be removed in a future PR that changes the functionality.
No functionality changes, so existing tests must pass as-is.
=> Refactoring for network span support

BugsnagPerformance.xcodeproj/project.pbxproj, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation/NSURLSession+Instrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation/NSURLSessionTask+Instrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation/NSURLSessionTask+Instrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, Sources/BugsnagPerformance/Private/Swizzle.h, Sources/BugsnagPerformance/Private/Swizzle.mm, features/automatic_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/AutoInstrumentNetworkNoParentScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentNetworkWithParentScenario.swift, features/steps/app_steps.rb
Network requests were being started and stopped at the end of a network request, which doesn't work well for nested spans because you can end up with the wrong parent.
This PR swizzles `NSURLSessionTask`'s `resume` method, establishing parentage at that point, and then ends the span once the metrics are collected.
New e2e tests to check parentage.
=> [PLAT-9743] Start and stop network spans at correct points instead of starting and stopping at the end

BugsnagPerformance.xcodeproj/project.pbxproj, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceViewType+Private.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceViewType.mm, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, Sources/BugsnagPerformance/Private/SpanAttributesProvider.h, Sources/BugsnagPerformance/Private/SpanAttributesProvider.mm, Sources/BugsnagPerformance/Private/Tracer.mm, features/automatic_spans.feature
All span attribute names are now centralized in `SpanAttributesProvider`.
Fixed misnamed attribute name (was `app_start`, now `app_start_phase`).
Updated tests to check for this.
=> Centralize and fix attribute names

CHANGELOG.md, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, Tests/BugsnagPerformanceTests/ViewControllerSpanTests.mm
Disable swizzling of `viewWillDisappear` for now until a better solution can be built.
The swizzle code could cause crashes in some multithreaded situations.
=> [Plat-10076] Disable viewWillDisappear swizzling

Sources/BugsnagPerformance/Private/SpanOptions.h, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpanOptions.m, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanOptions.h, Tests/BugsnagPerformanceTests/SpanOptionsTests.mm
Span option `makeContextCurrent` should be named `makeCurrentContext`
=> [PLAT-10066] Rename makeContextCurrent to makeCurrentContext

Sources/BugsnagPerformance/Private/SpanAttributesProvider.mm
It looks like `NSURLSessionTaskMetrics.transactionMetrics` can sometimes get swapped out for an empty `__NSArray0` on a different thread while the task delegate that was passed these metrics is still running, causing code like the following to crash with an index out of range error:
```objc
if (metrics.transactionMetrics.count > 0) {
NSString *protocolName = metrics.transactionMetrics[0].networkProtocolName;
```
This PR saves the current `transactionMetrics` locally before testing if it has contents.
=> Fix potential race condition in accessing NSURLSessionTaskMetrics.transactionMetrics

BugsnagPerformance.xcodeproj/project.pbxproj, Sources/BugsnagPerformance/Private/Span.h, Sources/BugsnagPerformance/Private/SpanOptions.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Private/Utils.h, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm, Tests/BugsnagPerformanceTests/SpanContextStackTests.mm, Tests/BugsnagPerformanceTests/SpanOptionsTests.mm, Tests/BugsnagPerformanceTests/SpanTests.mm
Events like time zone changes, daylight savings and NTP updates can cause the wall clock to skew, giving shortened spans or even spans with a start time before the end time. We want to counter this where we can.
When the span start time was the current time, and the end time is the current time, use monotonic clock info to adjust the end time in case any clock skew occurred.
Added unit tests to make sure the time calculation is accurate.
=> [PLAT-9978] Use monotonic clock to counter time skew

CHANGELOG.md, Example/Example/ViewController.swift, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.mm, features/automatic_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/AutoInstrumentNetworkBadAddressScenario.swift
If a network request fails (meaning it didn't even get a response from the server), don't record a span for it.
Added e2e test
=> [PLAT-10063] Don't send network spans for failed requests

CHANGELOG.md, Sources/BugsnagPerformance/Private/SpanData.h, Sources/BugsnagPerformance/Private/SpanData.mm, Tests/BugsnagPerformanceTests/SpanTests.mm
It's still technically possible in the early stages of span generation to access the span's attributes in a multithreaded way. Protect against this with a mutex.
Added unit test for this.
=> [PLAT-10154] Protect span attributes with a mutex

CHANGELOG.md, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanContext.h
`static_assert` is a C++ operation, which shouldn't be in public headers (they need to work with `.m` files).
These asserts aren't actually needed since the sizes are already guaranteed by the C and CLANG specs.
Removed the static asserts
None needed.
=> Remove C++ code from public headers

features/fixtures/ios/Fixture/Fixture.swift, features/fixtures/ios/Fixture/ViewController.swift, features/fixtures/ios/Scenarios/AutoInstrumentAppStartsScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentFileURLRequestScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentNetworkBadAddressScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentNetworkNoParentScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentNetworkWithParentScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentSubViewLoadScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentViewLoadScenario.swift, features/fixtures/ios/Scenarios/BackgroundForegroundScenario.swift, features/fixtures/ios/Scenarios/BatchingScenario.swift, features/fixtures/ios/Scenarios/BatchingWithTimeoutScenario.swift, features/fixtures/ios/Scenarios/FirstClassNoScenario.swift, features/fixtures/ios/Scenarios/FirstClassYesScenario.swift, features/fixtures/ios/Scenarios/InitialPScenario.swift, features/fixtures/ios/Scenarios/ManualNetworkSpanScenario.swift, features/fixtures/ios/Scenarios/ManualSpanBeforeStartScenario.swift, features/fixtures/ios/Scenarios/ManualSpanScenario.swift, features/fixtures/ios/Scenarios/ManualUIViewLoadScenario.swift, features/fixtures/ios/Scenarios/ManualViewLoadScenario.swift, features/fixtures/ios/Scenarios/ParentSpanScenario.swift, features/fixtures/ios/Scenarios/ProbabilityExpiryScenario.swift, features/fixtures/ios/Scenarios/ReleaseStageNotEnabledScenario.swift, features/fixtures/ios/Scenarios/RetryScenario.swift, features/fixtures/ios/Scenarios/SamplingProbabilityZeroScenario.swift, features/steps/app_steps.rb
With this PR, maze runner can now invoke arbitrary functions on the scenario:
```
Scenario: My scenario
Given I run "MyScenario"
And I wait for 1 span
...
And I invoke "sendMoreSpans"
And I wait for 3 spans
...
```
Tested manually. Updated e2e tests will come in a future PR.
=> Add support for invoking functions on the current scenario

features/automatic_spans.feature
We can't guarantee that the automatic load view spans will always be in the same trace, so this test can't check `Bugsnag-Span-Sampling` without becoming flaky.
=> Remove Bugsnag-Span-Sampling header check on AutoInstrumentViewLoadScenario

Sources/BugsnagPerformance/Private/OtlpUploader.mm
`NSISO8601DateFormatWithFractionalSeconds` is not valid on iOS < 11.2. Put a guard in for it.
=> Fix ISO8601DateFormatter crash on iOS < 11.2

features/initial-p-value.feature
Due to the timing of this test, it's possible for two P value requests to be sent in certain edge cases.
=> Allow for multiple P value requests in ProbabilityExpiryScenario

features/fixtures/ios/Scenarios/InitialPScenario.swift, features/fixtures/ios/Scenarios/RetryScenario.swift, features/initial-p-value.feature, features/manual_spans.feature
Some of the e2e tests were relying on delays, which can sometimes flake. Instead, use callbacks for better synchronization between mazerunner and the scenarios.
=> Use callbacks to make some e2e tests more robust

Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.mm
The UI app start span was getting its start time from an uninitialized value (which was the wrong variable to pull from).
Also manually set the parentage for app start spans to make sure spurious spans made during app startup don't accidentally insert themselves into the middle of the hierarchy.
Manually tested.
=> [PLAT-10251] Fix incorrect ui span start time

BugsnagPerformance.xcodeproj/project.pbxproj, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/Persistence.h, Sources/BugsnagPerformance/Private/Persistence.mm, Sources/BugsnagPerformance/Private/PersistentDeviceID.h, Sources/BugsnagPerformance/Private/PersistentDeviceID.mm, Sources/BugsnagPerformance/Private/PersistentState.h, Sources/BugsnagPerformance/Private/PersistentState.mm, Sources/BugsnagPerformance/Private/ResourceAttributes.h, Sources/BugsnagPerformance/Private/ResourceAttributes.mm, Sources/BugsnagPerformance/Private/Tracer.mm, Tests/BugsnagPerformanceTests/PersistenceTests.mm, Tests/BugsnagPerformanceTests/PersistentDeviceIDTest.mm, Tests/BugsnagPerformanceTests/PersistentStateTests.mm, Tests/BugsnagPerformanceTests/ResourceAttributesTests.mm
This PR makes the device ID generation reliable and repeatable.
We use the same algorithm as bugsnag-cocoa, but also account for the Apple APIs failing, in which case we seed from a random UUID.
The generated device ID is persisted across launches. Device ID persistence goes into a separate "bugsnag-shared" directory off the top cache dir so that the same algorithm can later be implemented in bugsnag-cocoa.
Note: Clearing persistence does *not* clear the "bugsnag-shared" directory.
Some classes needed to be converted over to `PhasedStartup`.
Added tests to ensure the stability and robustness of the algorithm.
=> [Plat-10168] device-id improvements

BugsnagPerformance.xcodeproj/project.pbxproj, BugsnagPerformanceTestsApp/BugsnagPerformanceTestsApp-Bridging-Header.h, CHANGELOG.md, Sources/BugsnagPerformance/Private/BugsnagPerformanceConfiguration+Private.h, Sources/BugsnagPerformance/Private/PersistentState.h, Sources/BugsnagPerformance/Private/PersistentState.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceConfiguration.mm, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceConfiguration.h, Tests/BugsnagPerformanceTests/PersistentStateTests.mm, Tests/BugsnagPerformanceTestsSwift/PerformanceMicrobenchmarkTests.swift, features/fixtures/ios/Scenarios/SamplingProbabilityZeroScenario.swift, features/fixtures/ios/Scenarios/Scenario.swift
Remove public access to the `samplingProbability` config option because it gets too confusing when mixed with server-side P values.
=> Remove public access to the samplingProbability config option

Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.mm, features/automatic_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/AutoInstrumentNetworkMultiple.swift
Network spans must have their `makeCurrentContext` explicitly set to false because the default is true, and we don't want network spans to become parents of other spans.
Added e2e test
=> [PLAT-10310] Ensure that network spans don't become parents

Sources/BugsnagPerformance/Private/PersistentDeviceID.h, Sources/BugsnagPerformance/Private/PersistentDeviceID.mm, Sources/BugsnagPerformance/Private/ResourceAttributes.mm, Tests/BugsnagPerformanceTests/PersistentDeviceIDTest.mm
Make the persistent device ID code match https://github.com/bugsnag/bugsnag-cocoa/pull/1568 as closely as possible.
Both codebases must produce exactly the same ID values, in the same JSON structure, written to the same file location.
Furthermore, both codebases must preserve any existing "external" device ID to handle the upgrade path from the already released code that doesn't contain an "internal" device ID.
=> Update persistent device id code to match bugsnag-cocoa

CHANGELOG.md, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, features/automatic_spans.feature, features/fixtures/ios/Scenarios/AutoInstrumentSubViewLoadScenario.swift
Made sure that each ViewLoadPhase is reported only once. This allows us to avoid duplicates in case of ViewControllers that override a particular phase and call super.
=> [PLAT-10570] Removed duplicate ViewLoadPhase spans

Gemfile.lock, Sources/BugsnagPerformance/Private/BugsnagPerformanceConfiguration+Private.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/OtlpPackage.h, Sources/BugsnagPerformance/Private/OtlpPackage.mm, Sources/BugsnagPerformance/Private/OtlpTraceEncoding.mm, Sources/BugsnagPerformance/Private/OtlpUploader.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceConfiguration.mm, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/MaxPayloadSizeScenario.swift, features/manual_spans.feature, features/steps/app_steps.rb
If a failed request contained an (uncompressed) payload size over the limit, don't retry; just throw it out.
Added e2e test.
=> [PLAT-10185] Throw out failed payloads that are oversized

Sources/BugsnagPerformance/Private/SpanData.mm
Just to be 1000% sure, cover all span attribute mutation cases with a mutex lock, even if the code won't run multithreaded at this time. This ensures that any future code changes won't accidentally trigger a regression.
=> Cover all attribute mutation cases with a mutex to avoid future problems

Sources/BugsnagPerformance/Private/Span.h
We've been experiencing an overflow in very rare cases when calculating end time using the system monotonic clock. To better understand what's going on, do a signed subtraction instead so that we can measure the magnitude of the effect going forward.
=> Perform end time calculation using signed ints to prevent unsigned overflow

BugsnagPerformance.xcodeproj/project.pbxproj, CHANGELOG.md, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceSpan+Private.h, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.mm, Sources/BugsnagPerformance/Private/Span.h, Sources/BugsnagPerformance/Private/SpanAttributesProvider.mm, Sources/BugsnagPerformance/Private/SpanData.h, Sources/BugsnagPerformance/Private/SpanData.mm, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceNetworkRequestInfo.m, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformance.h, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceConfiguration.h, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceNetworkRequestInfo.h, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/AutoInstrumentNetworkCallbackScenario.swift, features/fixtures/ios/Scenarios/ManualNetworkCallbackScenario.swift, features/network.feature
Allow more user control over network spans.
Configuration now allows the user to set a callback that will be called on every network span, allowing the reported URL to be changed, or even causing the entire span to be dropped and not reported.
Added new e2e tests.
=> [PLAT-10621] Allow users to control network spans via callback mechanism

.buildkite/pipeline.yml, .gitignore
Capture unit test logs.
Note that logs are only copied into place by the script when tests fail, so successful builds will not have any build artifacts attached.
Tested by forcing a unit test failure in a temporary commit - the artifacts were attached to the Buildkite step as expected.
=> Capture unit test logs

Gemfile.lock, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceLibrary.mm, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation/NSURLSessionTask+Instrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, Sources/BugsnagPerformance/Private/Tracer.h
There were some subtle issues with the existing swizzled methods that are fixed in this PR.
- BugsnagPerformanceLibrary's callback was changed to a C++ lambda so that we can use copy semantics since `bugsnagPerformanceImpl_` is a smart pointer that could invalidate when the stack went away.
- Harmonized all swizzled methods to use the same approach.
- Separated each view swizzle into a separate method to avoid accidental local variable bleeding.
- Check for nil before calling the original method implementation when swizzling.
- Mark all local variables used in swizzled methods `__block` (not strictly necessary in all cases, but safer all around)
Tested manually on the example app, re-ran e2e tests.
=> [PLAT-10958] Fix some subtle swizzling bugs

Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.mm, features/default/automatic_spans.feature
Rename the cold/warm start spans so that they can be better differentiated when using native platforms with languages like RN.
Updated e2e tests.
=> [PLAT-10845] Rename [AppStart/Cold] with [AppStart/iOSCold] and [AppStart/Warm] with [AppStart/iOSWarm]

.gitignore, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceLibrary.mm, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, features/fixtures/ios/Scenarios/Scenario.swift, features/fixtures/ios/build.sh
Using `networkRequestCallback_` null value as a flag affecting behaviour is too fragile and has led to multiple bugs. Refactor this section to just re-run the callback for the (max 10 or so) initial spans instead, which makes the concurrency checks far less complex / prone to holes.
As a result:
- `isEarlySpansPhase_` and dependent code will never suffer race conditions
- Spans will never end up partially initialized because they ran in between states where the network callback pointed to actual user code.
- The callbacks can never be null
=> Ensure span cancellation is done properly with concurrency protection

BugsnagPerformance.xcodeproj/project.pbxproj, Sources/BugsnagPerformance/Private/EarlyConfiguration.h, Sources/BugsnagPerformance/Private/EarlyConfiguration.mm, Sources/BugsnagPerformance/Private/Span.h, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpan.h, Tests/BugsnagPerformanceTests/TracerTests.mm
When view spans are started during the prewarm phase, throw them out because they'll end up with long durations that skew the dashboard stats.
Added uni tests.
=> [Plat-10875] Prewarm view spans

Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation/NSURLSessionTask+Instrumentation.mm, Tests/BugsnagPerformanceTests/BugsnagPerformanceConfigurationTests.mm
Getting the list of `NSURLSession` classes on the main thread runs the risk of a deadlock in later iOS versions, so do it on a dispatch queue instead.
=> Network swizzle timing

Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformance.mm, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformance.h, features/default/manual_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/ManualViewLoadPhaseScenario.swift
Adds a swift-accessible API for view load phase spans, which will be used in the upcoming SwiftUI instrumentation API.
Added e2e test
=> [PLAT-11205] Add view load phase API that can be called from Swift

.buildkite/pipeline.yml
Increase Buildkite e2e test job timeouts to avoid unnecessary build failures when there are delays in provisioning a test device.
Covered by CI.
=> Increase e2e test job timeouts

.buildkite/pipeline.yml, BugsnagPerformance.podspec.json, BugsnagPerformance.xcodeproj/project.pbxproj, BugsnagPerformanceSwiftUI.podspec.json, BugsnagPerformanceSwiftUI/BugsnagPerformanceSwiftUI.docc/BugsnagPerformanceSwiftUI.md, BugsnagPerformanceSwiftUI/BugsnagPerformanceSwiftUI.h, BugsnagPerformanceSwiftUITests/BugsnagPerformanceSwiftUITests.swift, Example/Example.xcodeproj/project.pbxproj, Example/Example/SomeView.swift, Makefile, Package.swift, Sources/BugsnagPerformance/Private/SpanAttributesProvider.mm, Sources/BugsnagPerformanceSwiftUI/BugsnagPerformanceSwiftUIInstrumentation.swift, features/default/automatic_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/AutoInstrumentSwiftUIScenario.swift, features/steps/app_steps.rb
This PR adds support for instrumenting SwiftUI views.
Views can be instrumented by wrapping them in a `BugsnagTracedView`, or by calling the view extension function `bugsnagTraced`:
```swift
import SwiftUI
import BugsnagPerformanceSwiftUI
struct ContentView: View {
var body: some View {
VStack {
Image(systemName: "globe")
.imageScale(.large)
.foregroundStyle(.tint)
Text("Hello, world!")
}
.padding()
.bugsnagTraced("My traced view")
}
}
```
Added e2e tests
=> [PLAT-11206] Add SwiftUI instrumentation

Makefile
The makefile wasn't including `BugsnagPerformanceSwiftUI.podspec.json` in the release commit.
=> Include SwiftUI podspec in release process

Dangerfile
Add the same Danger reporting as bugsnag-cocoa to show absolute size of framework and summary of the net change.
=> build: added absolute framework size to dangerfile

BugsnagPerformance.xcodeproj/project.pbxproj, Sources/BugsnagPerformance/Private/AppStateTracker.h, Sources/BugsnagPerformance/Private/AppStateTracker.m, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Private/WeakSpansList.h, Sources/BugsnagPerformance/Private/WeakSpansList.mm, Tests/BugsnagPerformanceTests/WeakSpansListTests.mm
Spans that are still open when the app is backgrounded will end up with ridiculously long durations. Throw out unended spans when backgrounding the app instead.
Since we can't automate app backgrounding in a reliable way, I tested this manually.
The new weak span list component also has unit tests.
=> [PLAT-11315] Discard unfinished spans when the app goes into the background

features/default/initial-p-value.feature, features/fixtures/ios/Scenarios/InitialPScenario.swift
Guessing that the initial P value scenario might sometimes start sending spans before it has received the P value response from the server, delay creating any spans for awhile to give time for the response to be received, even if it is a little slow.
=> [PLAT-11269] Delay the initial P value scenario

.buildkite/pipeline.yml, Gemfile, Gemfile.lock, features/default/automatic_spans.feature, features/fixtures/ios/Scenarios/AutoInstrumentNetworkBadAddressScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentNetworkCallbackScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentNetworkMultiple.swift, features/fixtures/ios/Scenarios/AutoInstrumentNetworkNoParentScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentNetworkWithParentScenario.swift, features/fixtures/ios/Scenarios/ManualNetworkCallbackScenario.swift, features/fixtures/ios/Scenarios/Scenario.swift
Ignore internal network requests in e2e tests.
The `/command` and `/metrics` Maze Runner endpoints should be completely ignored by the e2e tests.
Covered by CI.
=> Ignore internal network requests in e2e tests

Sources/BugsnagPerformance/Private/WeakSpansList.h
The `count` method of weak span list wasn't protected by a mutex, causing TSAN issues.
=> [PLAT-11456] Make sure all paths of weak span list are protected with a mutex

Sources/BugsnagPerformance/Private/BugsnagPerformanceSpan+Private.h, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, Sources/BugsnagPerformance/Private/Span.h, Sources/BugsnagPerformance/Private/SpanAttributesProvider.h, Sources/BugsnagPerformance/Private/SpanAttributesProvider.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm, features/fixtures/ios/Fixture/Fixture.swift
Adjust view load spans for pre-loaded views so they reflect the actual time it took to load the view.
If the view is detected as pre-loaded on viewWillAppear, the span start time is adjusted and the view name is appended with "(pre-loaded)" suffix
View load span adjustments on viewWillAppear
Removed the viewWillDisappear fallback which was also causing very long spans that weren't necessarily even presented to the User
=> Fixes for pre-loaded views instrumentation

BugsnagPerformance.podspec.json, CHANGELOG.md
Installing Bugsnag using Cocoapods was causing file collisions if the app had its own PrivacyInfo file
Avoid the collisions by using resource_bundles instead of resources
Replaces resources with resource_bundles in the podspec
Manual testing on an example app
=> Fixed the issue causing PrivacyInfo collisions when using Cocoapods

Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm
This section of code was incorrectly holding a pointer to the result of `NSString.UTF8String` beyond the original string's lifetime, resulting in ASAN errors.
Just use the Objective-C String class directly for the string comparisons.
=> Use ObjC strings instead of C strings to avoid lifetime race condition

.buildkite/pipeline.yml
Use Xcode 15.2 for CI builds, the latest currently available (Xcode 15.3 on macOS 14 is coming soon).
Covered by CI.
=> Use Xcode 15.2 for CI builds

CHANGELOG.md, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.mm, features/default/automatic_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Fixture/Fixture-Bridging-Header.h, features/fixtures/ios/Scenarios/AutoInstrumentNetworkNullURLScenario.swift, features/fixtures/ios/Scenarios/ObjCURLSession.h, features/fixtures/ios/Scenarios/ObjCURLSession.m
Any spans created before Bugsnag is initialized get stored in an "early spans" list. There is an edge case where a URL request with a nil URL causes the span code to return a nil span, which crashes when we try to add the resulting nil pointer to the "early spans" list.
Add a nil guard around the span code.
Added repro case as an e2e test.
=> [PLAT-11750] Handle edge case when capturing a URL request with a null URL before Bugsnag is initialized

BugsnagPerformanceSwift.podspec.json, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, features/default/automatic_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/ViewDidLoadDoesntTriggerScenario.swift
There are edge cases in UIKit container classes whereby a child's `viewDidAppear` will be delayed by a huge amount (for example from an incomplete swipe to a new view). This throws out our view load span durations.
When we detect a long delay after `viewDidLayoutSubviews` where `viewDidAppear` still hasn't been called, assume that this edge case has been triggered and use the time of `viewDidLayoutSubviews` instead.
Added e2e test.
=> [Plat-11738] viewDidAppear edge case

features/default/automatic_spans.feature, features/fixtures/ios/Scenarios/AutoInstrumentGenericViewLoadScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentNavigationViewLoadScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentPreLoadedViewLoadScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentSubViewLoadScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentTabViewLoadScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentViewLoadScenario.swift, features/fixtures/ios/Scenarios/ComplexViewScenario.swift, features/steps/app_steps.rb
Remove the effective 10 second delay between commands issued by maze runner.
Some old code was improperly imposing a 10s delay between all commands.
=> Karl fix 10 second delay

Sources/BugsnagPerformance/Private/AppStateTracker.h, Sources/BugsnagPerformance/Private/AppStateTracker.m, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/Instrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/Instrumentation.mm, Sources/BugsnagPerformance/Private/OtlpTraceEncoding.mm, Sources/BugsnagPerformance/Private/Span.h, Sources/BugsnagPerformance/Private/SpanData.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Private/WeakSpansList.h, Sources/BugsnagPerformance/Private/Worker.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceConfiguration.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpan.h, Tests/BugsnagPerformanceTests/WorkerTests.mm, features/fixtures/ios/Scenarios/Scenario.swift
If the app is backgrounded before starting Bugsnag, any early spans opened before this were remaining active instead of being cancelled. This led to incredibly long app start spans in some cases.
There are also cases where the app startup was getting interrupted for unknown reasons, also resulting in unnaturally long app startup spans.
We need to mitigate these edge cases.
Check for both a long app start time, and the app being backgrounded immediately after start. In both cases, we discard the app startup spans.
Since notifications can be received before the app starts (and thus before Bugsnag is started), connect the notifications in the early setup code rather than in the start code.
Track `NSApplicationDidFinishLaunchingNotification` and use it to detect unnaturally long app launches …
=> [PLAT-12032] Detect app backgrounding earlier so we can cancel spans

CONTRIBUTING.md
- Added a CONTRIBUTING.md to the repo
- Used the first few sections of the contribution guide from bugsnag-cocoa and adapted it for bugsnag-cocoa-performance
=> Adding a contributing guide to cocoa performance

BugsnagPerformance.xcodeproj/project.pbxproj, Sources/BugsnagPerformance/Private/BugsnagPerformanceCrossTalkAPI.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceCrossTalkAPI.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Tests/BugsnagPerformanceTests/CrossTalkTests.m
Add a cross-talk API. This API can be connected to by another native library (and is being added to bugsnag-cocoa here: https://github.com/bugsnag/bugsnag-cocoa/pull/1649 )
The cross-talk API is a well-known, uniquely named class (`BugsnagPerformanceCrossTalkAPI`) that can be loaded by name from native code in another library using `NSClassFromString()`.
The calling code can then request that a named API be mapped to a particular selector using `mapAPINamed:toSelector:`. All methods are mapped onto `BugsnagPerformanceCrossTalkAPI` itself.
The mapping request includes a string representing the method the caller wants, and the selector they are expecting to use.
```objc
[cls mapAPINamed:@"getCurrentTraceAndSpanIdV1" toSelector:@selector(getCurrentTraceAndSpanId)];
```
If we're not willing …
=> [PLAT-12123] Add cross-talk API

.buildkite/pipeline.yml
Temporarily skip iOS 17 tests due to device farm issues.
Covered by CI.
=> Temporarily skip iOS 17 tests due to device farm issues

.buildkite/pipeline.yml, features/default/automatic_spans.feature, features/default/manual_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj
Change test fixture bundle identifier to all lower case, allowing us to reinstate iOS 17 testing.
Something in the Appium stack must have change to make the bundle identifier sensitive in testing, but this seem to be a reasonable change to make in response to that.
Covered by CI.
=> Change test fixture bundle identifier to all lower case

Sources/BugsnagPerformance/Private/Batch.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceSpan+Private.h, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.mm, Sources/BugsnagPerformance/Private/NetworkHeaderInjector.mm, Sources/BugsnagPerformance/Private/OtlpTraceEncoding.mm, Sources/BugsnagPerformance/Private/OtlpUploader.mm, Sources/BugsnagPerformance/Private/Span.h, Sources/BugsnagPerformance/Private/SpanAttributesProvider.h, Sources/BugsnagPerformance/Private/SpanAttributesProvider.mm, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Private/Utils.h, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm, features/default/automatic_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/AutoInstrumentAVAssetScenario.swift
Apple breaks their own `NSURLSessionTask` APIs by throwing exceptions to mark them as unsupported, so we must work around this or else we'll crash.
Affected APIs are now guarded with try/catch, and a new attribute field `bugsnag.instrumentation_message` has been added to allow reporting the error to the backend.
Because the request can't be fetched from an `AVAssetDownloadTask`, it never goes through a metrics collection phase either, meaning that we can only rely upon the destructor for closing the span. This behaviour can be triggered by calling `endOnDestroy` on the span (which we now do whenever we fail to fetch a request from a task).
I've also added some permanent trace and debug logging because I got tired of adding it every time something breaks :P
New e2e tests that check using …
=> [PLAT-12192] Catch badly behaved Apple APIs and report any errors generated rather than crashing

Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, features/default/automatic_spans.feature
The check for `makeCurrentContext` was being done both in `BugsnagPerformanceImpl.mm` and `Tracer.mm`, causing it to double-add to the stack, making them leak.
Remove the implementation in `BugsnagPerformanceImpl.mm`
Reran all tests to make sure nothing was accidentally depending on this (anything that is must be checked for correctness).
=> [PLAT-12205] Remove duplicate makeCurrentContext check

CHANGELOG.md, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, features/default/manual_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/ManualNetworkSpanCallbackNotSetScenario.swift, features/fixtures/ios/Scenarios/ManualNetworkSpanCallbackSetToNilScenario.swift
Prevent a crash when User calls reportNetworkRequestSpan without setting networkRequestCallback on BugsnagPerformanceConfiguration
Added a safeguard preventing a null being assigned to networkRequestCallback_ in BugsnagPerformanceImpl class
E2E tests
=> Fixed a crash on reportNetworkRequestSpan

BugsnagPerformance.xcodeproj/project.pbxproj, CHANGELOG.md, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/SpanOptions.h, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformance.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpanContext.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpanOptions.m, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformance.h, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpan.h, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanContext.h, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanOptions.h, features/default/manual_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/ManualParentSpanScenario.swift
Setting the parent ID of a span required an existing Bugsnag span, which made it impossible to receive a span from an outside source and make it a parent of a Bugsnag span.
`BugsnagPerformanceSpan` has been made a subclass of `BugsnagPerformanceSpanContext`, and the APIs relating to span parentage have been updated to take a `BugsnagPerformanceSpanContext` (or subclass) instead.
The API changes will not break existing usage since it's technically more permissive than before.
Added a new e2e test.
=> [PLAT-12317] Allow setting the parent context by span ID and trace ID rather than requiring an actual span object

BugsnagPerformance.xcodeproj/project.pbxproj, CHANGELOG.md, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.mm, Sources/BugsnagPerformance/Private/SpanOptions.h, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformance.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpanContext.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpanOptions.m, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformance.h, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpan.h, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanContext.h, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanOptions.h, features/default/manual_spans.feature, features/default/network.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/AutoInstrumentNullNetworkCallbackScenario.swift, features/fixtures/ios/Scenarios/ManualParentSpanScenario.swift
If the user manually sets the network callback to nil, it could crash the app.
I've also added more logging to help diagnose a networking issue on a customer site.
Don't set a default implementation, and always check the callback pointer no matter what.
New e2e test
=> Verify network callback pointer

.buildkite/pipeline.yml
Builds an XCFramework for the library each time CI runs, attaching it as a build artifact (compressed).
Covered by CI.
=> Build an XCFramework on CI

Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceSpan+Private.h, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, Sources/BugsnagPerformance/Private/OtlpTraceEncoding.mm, Sources/BugsnagPerformance/Private/Span.h, Sources/BugsnagPerformance/Private/SpanData.h, Sources/BugsnagPerformance/Private/SpanData.mm, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpan.h, Tests/BugsnagPerformanceTests/SpanStackingHandlerTests.mm, Tests/BugsnagPerformanceTests/SpanTests.mm, features/default/manual_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/SetAttributesScenario.swift
Renamed span.addAtribute to setAttribute and exposed it in the public headers.
Setting an attribute to nil now erases that attribute.
Setting an invalid attribute type now prints an error message when encoding.
Added new unit tests and e2e tests.
=> Expose span.setAttribute

features/fixtures/ios/Fixture/FixtureConfig.swift, features/fixtures/ios/Scenarios/AutoInstrumentAVAssetScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentNetworkBadAddressScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentNetworkCallbackScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentNetworkMultiple.swift, features/fixtures/ios/Scenarios/AutoInstrumentNetworkNoParentScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentNetworkNullURLScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentNetworkWithParentScenario.swift, features/fixtures/ios/Scenarios/ManualNetworkCallbackScenario.swift, features/fixtures/ios/Scenarios/Scenario.swift
The e2e tests were getting messy because filtering for mazerunner admin URLs had evolved over time, differently for different tests.
All e2e tests now filter ALL mazerunner URLs by default, and all mazerunner URLs are now defined in one place only.
=> All e2e tests now filter out the same admin URLs by default

Sources/BugsnagPerformance/Private/BugsnagPerformanceLibrary.mm, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Private/Worker.mm, features/default/automatic_spans.feature, features/fixtures/ios/Scenarios/AutoInstrumentAppStartsScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentNetworkCallbackScenario.swift
Many of the top-level calls don't have autoreleasepools, and are leaking. Although not many things are leaking, they're still leaking.
This PR adds autoreleasepools to the top-level calls, and also defensively to Worker so that it doesn't retain things for too long.
Tracer was causing a strong recursive retain of the spans being created, which has now been fixed.
=> Add autoreleasepools at top level calls

CHANGELOG.md, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/OtlpTraceEncoding.h, Sources/BugsnagPerformance/Private/OtlpTraceEncoding.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceConfiguration.mm, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceConfiguration.h, Tests/BugsnagPerformanceTests/OtlpTraceEncodingTests.mm, features/default/configuration.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/FixedSamplingProbabilityOneScenario.swift, features/fixtures/ios/Scenarios/FixedSamplingProbabilityScenario.swift, features/fixtures/ios/Scenarios/FixedSamplingProbabilityZeroScenario.swift
To support non-BugSnag trace endpoints, we should provide the client RUM SDKs with a samplingProbability configuration that can be set by the developer to provide a fixed p-value for sampling.
When sampling probability is set it:
- disables the initial and periodic p-value requests being sent
- is used in preference to any persisted p-value or any value received in response headers
- disables the setting of the Bugsnag-Span-Sampling header, but keep the bugsnag.sampling.p attribute for possible future use
Added `samplingProbability` option to `BugsnagPerformanceConfiguration`
E2E and Unit tests
=> Sampling probability configuration option

CHANGELOG.md, Sources/BugsnagPerformance/Private/PhasedStartup.h, Sources/BugsnagPerformance/Private/Tracer.mm, features/default/automatic_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/EarlySpanOnEndScenario.swift
Spans ended before the library was started can't call the OnSpanEnd callbacks because they haven't been configured yet.
On library start, explicitly call the OnSpanEnd callbacks for all spans ended before the library started.
Added e2e test
=> [Plat-12551] Call OnSpanEnd callbacks for early spans on library start

Sources/BugsnagPerformance/Private/BugsnagPerformanceSpan+Private.h, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm, Tests/BugsnagPerformanceTests/SpanTests.mm, features/default/automatic_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/ModifyEarlySpansScenario.swift
Spans shouldn't be modified after they have ended or been aborted.
Disallow span mutations after they have been closed, and issue error messages when an attempt is made.
Mutability is temporarily re-enabled for early spans that ended before the library started so that the onSpanEnd callbacks can be run.
Added new e2e test and unit tests.
=> [PLAT-12452] Enforce immutability on closed spans

.buildkite/pipeline.yml, scripts/build-xcframework.sh
Pretty much does as described, copies the XCframework products up to the top level once built and zips them there, rather than the whole directory structure.
@kstenerud I'd appreciate you checking the zip file on the build step, just to make sure everything is there.
=> Upload only the XCframework product without excess directories

BugsnagPerformance.podspec.json, BugsnagPerformanceSwift.podspec.json, CHANGELOG.md
When using `**/*` as the glob specifier for source files, the `xcprivacy` file also gets sucked in and generates warnings. Use a more specific glob specifier so that non-compiled files don't get sucked in.
There was also one version reference that didn't get updated with the last PR. After this, it will be updated via the Makefile command.
=> [PLAT-12631] Prevent .xcprivacy files from being marked 'compile' in podspec

Sources/BugsnagPerformance/Public/BugsnagPerformanceConfiguration.mm, Tests/BugsnagPerformanceTests/BugsnagPerformanceConfigurationTests.mm
Our SaaS span endpoint now supports the format <project_api_key>.otlp.bugsnag.com.
Changed default endpoint in `BugsnagPerfromanceConfiguration`.
Unit tests
=> Updated default url

CHANGELOG.md, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceSpan+Private.h, Sources/BugsnagPerformance/Private/OtlpTraceEncoding.h, Sources/BugsnagPerformance/Private/OtlpTraceEncoding.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceConfiguration.mm, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceConfiguration.h, Tests/BugsnagPerformanceTests/BugsnagPerformanceConfigurationTests.mm, Tests/BugsnagPerformanceTests/OtlpTraceEncodingTests.mm, features/default/manual_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/SetAttributesWithLimitsScenario.swift, features/steps/app_steps.rb
Adds configurable size limits to string and array span attribute values.
These can be configured:
- `attributeStringValueLimit`
- `attributeArrayLengthLimit`
Added unit tests and e2e test.
=> [PLAT-12703] Add configurable size limits to span attributes

CHANGELOG.md, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceSpan+Private.h, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, Sources/BugsnagPerformance/Private/OtlpTraceEncoding.mm, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceConfiguration.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceConfiguration.h, Tests/BugsnagPerformanceTests/BatchTests.mm, Tests/BugsnagPerformanceTests/OtlpTraceEncodingTests.mm, Tests/BugsnagPerformanceTests/SamplerTests.mm, Tests/BugsnagPerformanceTests/SpanOptionsTests.mm, Tests/BugsnagPerformanceTests/SpanStackingHandlerTests.mm, Tests/BugsnagPerformanceTests/SpanTests.mm, Tests/BugsnagPerformanceTests/WeakSpansListTests.mm, features/default/manual_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/SetAttributeCountLimitScenario.swift
This is the second half to https://github.com/bugsnag/bugsnag-cocoa-performance/pull/314
=> Configurable limit to the number of attributes that can be added to a span

features/steps/app_steps.rb
All schemas and validation are called implicitly, and modified through configuration, we shouldn't call them explicitly at all.
=> Remove explicit trace calls

CHANGELOG.md, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.mm, features/default/automatic_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/AutoInstrumentNetworkPreStartDisabledScenario.swift, features/fixtures/ios/Scenarios/AutoInstrumentNetworkPreStartScenario.swift, features/swizzling_disabled/automatic_spans.feature
There was still a potential for early network spans to leak through even when disabled via configuration. This PR closes that hole.
Added new e2e tests.
=> [PLAT-12731] Make sure that no early network spans escape when automatic network span capture is disabled

CHANGELOG.md, Sources/BugsnagPerformance/Public/BugsnagPerformanceConfiguration.mm, Tests/BugsnagPerformanceTests/BugsnagPerformanceConfigurationTests.mm
These were missed in an earlier PR.
Updated unit tests to check for them.
=> [PLAT-12705] Add missing / misnamed fields to plist configuration

Sources/BugsnagPerformance/Private/FrameRateMetrics/FrameMetricsCollector.mm, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceConfiguration.mm, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanOptions.h
Don't send rendering metrics if total frames count is zero
Spans with rendering metrics and zero total frames look confusing so we decided not to display them
- Do not include rendering metrics if there are zero total frames
Existing E2E tests
=> Don't send rendering metrics if total frames count is zero

CHANGELOG.md, Package.swift, Sources/BugsnagPerformance/Private/ResourceAttributes.mm, Sources/BugsnagPerformance/Private/SpanAttributesProvider.mm
Fix some compilation issues that happen on visionOS.
visionOS isn't yet officially supported because we don't have tests for it, but it at least compiles and runs and sends spans.
=> [PLAT-12326] Fix visionOS compile issues

BugsnagPerformance.xcodeproj/project.pbxproj, CHANGELOG.md, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation/BSGPerformanceSharedSessionProxy.h, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation/BSGPerformanceSharedSessionProxy.mm, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation/NSURLSession+Instrumentation.mm, features/default/automatic_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/FixtureXcFramework.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/AutoInstrumentNetworkSharedSessionInvalidateScenario.swift
Fixed a crash after shared NSURLSession is invalidated and then used
In the Bugsnag SDK for iOS it replaces the [NSURLSession sharedSession] with another normal session by [method|this method](https://github.com/bugsnag/bugsnag-cocoa-performance/blob/next/Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation/NSURLSession%2BInstrumentation.mm#L41-L65).
While according to Apple, [here](https://developer.apple.com/documentation/foundation/nsurlsession/1407428-finishtasksandinvalidate%7Cdoc), the sharedSession is actually a little bit special, as finishTasksAndInvalidate and invalidateAndCancel should take no effect on the sharedSession. 
Otherwise, it will cause crash with
Task created in a session that has been invalidated when another task is created with the …
=> Fixed a crash after shared NSURLSession invalidate

Sources/BugsnagPerformance/Private/BugsnagPerformanceCrossTalkAPI.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceCrossTalkAPI.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceLibrary.mm, Tests/BugsnagPerformanceTests/CrossTalkTests.m
Adds a new method `getConfigurationV1` to the cross-talk API to allow reading the configuration passed to `start`.
This isn't used yet but will be required for the upcoming react native integration.
Added a configuration property to the crosstalk API, which is set in  `BugsnagPerformanceLibrary::configureLibrary`.
`getConfigurationV1` therefore returns nil if the SDK has not been configured (i.e. if `start` has not been called) 
Added a unit test for the new crosstalk method, and tested manually with a React Native project
=> Add method to get configuration via cross-talk API

CHANGELOG.md, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/SpanAttributesProvider.h, Sources/BugsnagPerformance/Private/SpanAttributesProvider.mm, Sources/BugsnagPerformance/Public/BugsnagPerformance.mm, features/default/manual_spans.feature
Custom spans now set attribute `bugsnag.span.category` to `custom`.
e2e tests have been updated to check for this.
=> [PLAT-12988] Set bugsnag.span.category to 'custom' for custom spans

.github/workflows/scorecard.yml
Adding the [OSSF scorecard](https://github.com/ossf/scorecard) action, generated through GitHub to facilitate rendering a badge in due course.
=> build: add OpenSSF scorecard action

.buildkite/block.full.yml, .buildkite/pipeline.full.yml, .buildkite/pipeline.yml
General tidy-up of the Buildkite pipeline to:
- Ensure all steps have an adequate but not excessive timeout
- Agent queues are explicitly stated in each file (even if a default is used)
- Generic `macos` queue is used instead of specific macOS versions where possible
Covered by a full CI run.
=> Buildkite pipeline tidy-up

Sources/BugsnagPerformance/Private/Batch.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceCrossTalkAPI.mm, Sources/BugsnagPerformance/Private/NetworkHeaderInjector.mm, Sources/BugsnagPerformance/Private/OtlpTraceEncoding.mm, Sources/BugsnagPerformance/Private/Sampler.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpanContext.mm, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanContext.h
Methods/properties that return a struct (such as `traceId` in `BugsnagPerformanceSpanContext`) cannot be proxied in the CrossTalk API and would crash if accessed through a proxy object.
This PR adds two new properties for `traceIDHi` and `traceIdLo` to `BugsnagPerformanceSpanContext` and updates internal code to never access `traceId` on a span or span context and use these new properties instead.
Relied on existing tests
=> Replace internal access to `traceId` property with `traceIdHi` and `traceIdLo`

Sources/BugsnagPerformance/Private/BugsnagPerformanceSpan+Private.h, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm
The RN library needs to be able to set the end time multiple times, so we need to split out:
- ending a span (marking the end time)
- closing the span and sending for processing (at which time it becomes immutable)
`BugsnagPerformanceSpan` now has two new internal APIs:
- `- (void)markEndTime:(NSDate *)endTime` to set the end time of the span (can be called multiple times)
- `- (void)sendForProcessing` to send for processing (idempotent, only performs operation once)
Existing tests are sufficient since the public `end` functions now call these functions.
=> [PLAT-31288] Split out ending a span and closing/sending for processing

Sources/BugsnagPerformance/Private/BugsnagPerformanceSpan+Private.h, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm, Tests/BugsnagPerformanceTests/BatchTests.mm, Tests/BugsnagPerformanceTests/OtlpTraceEncodingTests.mm, Tests/BugsnagPerformanceTests/SamplerTests.mm, Tests/BugsnagPerformanceTests/SpanOptionsTests.mm, Tests/BugsnagPerformanceTests/SpanStackingHandlerTests.mm, Tests/BugsnagPerformanceTests/SpanTests.mm, Tests/BugsnagPerformanceTests/WeakSpansListTests.mm
Since the end time can be set long before the span is closed, we need to update snapshots as the end time is set, not at close time.
=> [PLAT-13288] Update snapshots whenever a span's end time is set (not just when the span is closed)

Sources/BugsnagPerformance/Private/BugsnagPerformanceCrossTalkAPI.mm, Tests/BugsnagPerformanceTests/CrossTalkTests.mm
Add support for creating `BugsnagPerformanceSpanOptions` and `BugsnagPerformanceSpanContext` instances via the crosstalk API.
Added two new APIs to `BugsnagPerformanceCrossTalkAPI`:
- `- (BugsnagPerformanceSpanOptions *)newSpanOptionsV1`
- `- (BugsnagPerformanceSpanContext *)newSpanContextV1`
Both APIs return proxy-wrapped instances.
Added unit tests for the new crosstalk methods.
=> Add crosstalk API methods for creating span options and contexts

CHANGELOG.md, Package.swift
Removes the platform restriction on CoreTelephony since it's now available on all platforms.
This will allow building for Mac Catalyst targets (although this is not yet officially supported).
No tests yet since we do not officially support non-ios platforms.
=> Remove condition on CoreTelephony for Mac Catalyst

Package.swift
Disable assertions on release build. There's nothing in the library using assertions other than the API key check at the start, but if in future we do start using them more, it will be good to have them disabled on a release build.
Ref: https://github.com/bugsnag/bugsnag-cocoa/issues/1705
=> Disable assertions on release build

CHANGELOG.md, Sources/BugsnagPerformance/Private/Tracer.mm, features/default/manual_spans.feature
View load spans should have firstClass = no by default, and not set current context.
Updated tests
=> [PLAT-11294] View load spanfix for firstClass and set current context

Gemfile, Sources/BugsnagPerformance/Private/BugsnagPerformanceCrossTalkAPI.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceSpan+Private.h, Sources/BugsnagPerformance/Private/FrameRateMetrics/FrameMetricsCollector.mm, Sources/BugsnagPerformance/Private/Metrics.h, Sources/BugsnagPerformance/Private/SpanOptions.h, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceConfiguration.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpanOptions.m, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceConfiguration.h, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanOptions.h, Tests/BugsnagPerformanceTests/BatchTests.mm, Tests/BugsnagPerformanceTests/BugsnagPerformanceConfigurationTests.mm, Tests/BugsnagPerformanceTests/OtlpTraceEncodingTests.mm, Tests/BugsnagPerformanceTests/SamplerTests.mm, Tests/BugsnagPerformanceTests/SpanOptionsTests.mm, Tests/BugsnagPerformanceTests/SpanStackingHandlerTests.mm, Tests/BugsnagPerformanceTests/SpanTests.mm, Tests/BugsnagPerformanceTests/WeakSpansListTests.mm, features/fixtures/ios/Scenarios/FrameMetricsAutoInstrumentRenderingOffScenario.swift, features/fixtures/ios/Scenarios/FrameMetricsFronzenFramesScenario.swift, features/fixtures/ios/Scenarios/FrameMetricsNoSlowFramesScenario.swift, features/fixtures/ios/Scenarios/FrameMetricsNonFirstClassSpanInstrumentRenderingOnScenario.swift, features/fixtures/ios/Scenarios/FrameMetricsSlowFramesScenario.swift, features/fixtures/ios/Scenarios/FrameMetricsSpanInstrumentRenderingOffScenario.swift, scripts/run-unit-tests.sh
This simplifies the interface and avoids needing yet another tri-state type when CPU metrics are added in the next PR.
This also introduces metrics config and option objects, which will hold all of the different metric types.
Note: There is some CPU configuration stuff in here (but no implementations). It makes it easier to just split by file in this case, even though it doesn't make semantic sense between PRs.
Deprecations:
* `BugsnagPerformanceConfiguration .autoInstrumentRendering` has been deprecated. Please use `BugsnagPerformanceConfiguration. enabledMetrics. rendering` instead.
* `BugsnagPerformanceSpanOptions.instrumentRendering` has been deprecated. Please use `BugsnagPerformanceSpanOptions.metricsOptions.rendering` instead.
* The `BSGFirstClass` type has been deprecated. Please …
=> Replace tri-state types with a single type, deprecating their uses in public APIs

features/default/network.feature, features/fixtures/ios/Fixture/Fixture.swift, features/fixtures/ios/Scenarios/Scenario.swift, features/steps/app_steps.rb
Enhanced mazerunner functionality that will be used in the CPU metrics PR
=> Enhance mazerunner functionality to support CPU metrics tests

.github/workflows/scorecard.yml, .github/workflows/signing.yml
Pins the remaining existing GHA references to known commits.
=> build: pin remaining GHA dependencies

CHANGELOG.md, Gemfile, Sources/BugsnagPerformance/Private/Tracer.mm, features/default/manual_spans.feature, scripts/run-unit-tests.sh
Reverted the change that was causing ViewLoad spans to not show up on the Dashboard
E2E Tests
=> REVERTED: View load spans are now not first class by default, and don't set the current context.

Sources/BugsnagPerformance/Private/BugsnagPerformanceCrossTalkAPI.mm, Tests/BugsnagPerformanceTests/CrossTalkTests.mm
Callbacks in Crosstalk API were not called due to lack of array initialisation
Callback arrays are now initialised when Crosstalk API shared instance is created
Unit tests
=> WillEndUIInitSpanCallbacks and willEndViewLoadSpanCallbacks in Crosstalk API are not being called

CHANGELOG.md, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.mm, features/default/automatic_spans.feature
Make sure `bugsnag.app_start.first_view_name` is populated for app start spans.
The attribute used to be set at app start span in pre-main which was too early for a ViewLoad to have started
`bugsnag.app_start.first_view_name` is now updated when the first view is loaded after the app start span has started
E2E test
=> Fixed issue where bugsnag.app_start.first_view_name was missing for app start spans

.buildkite/pipeline.yml, Gemfile, features/steps/hooks.rb
Change the e2e tests to use the new Maze Runner Appium API, meaning that we detect and report driver failures.
I've also added the test fixture as a Buildkite artifact for convenience of locally running tests.
Covered by CI - I also ran a test locally to force a failure, checking that the syslog was retrieved as expected by the code that's been changed.
=> Do not use Maze.driver directly

BugsnagPerformance.xcodeproj/project.pbxproj, CHANGELOG.md
`MARKETING_VERSION` is required in order to generate a correct `Info.plist` in some situations, and has until now been missing from the `BugsnagPerformance-iOS` target. This PR adds the setting so that it matches the other targets in the project.
The removal of the `BugsnagPerformanceTests.mm` entry is just Xcode auto-cleaning the project file.
=> Add missing MARKETING_VERSION to BugsnagPerformance-iOS

CODEOWNERS, features/default/manual_spans.feature, features/default/metrics.feature, features/fixtures/ios/Scenarios/CPUMetricsScenario.swift, features/fixtures/ios/Scenarios/MemoryMetricsScenario.swift, features/fixtures/ios/Scenarios/OnEndCallbackScenario.swift, features/fixtures/ios/Scenarios/RenderingMetricsScenario.swift, features/fixtures/ios/Scenarios/Scenario.swift, features/fixtures/ios/Scenarios/SetAttributeCountLimitScenario.swift, features/fixtures/ios/Scenarios/SetAttributesScenario.swift, features/fixtures/ios/Scenarios/SetAttributesWithLimitsScenario.swift
Viewing spans created in some E2E tests on Dashboard is confusing because they are grouped under name "MySpan"
Changed span names in E2E tests so they include the scenario name and variant name (in case a scenario is reused in multiple tests)
E2E Tests
=> Made span names in E2E Tests more informative

CHANGELOG.md, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.h, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, features/default/automatic_spans.feature, features/fixtures/ios/Scenarios/ViewDidLoadDoesntTriggerScenario.swift, features/steps/app_steps.rb
ViewControllers were kept in memory for up to 10 seconds after being dismissed.
Removed a strong reference holding ViewControllers for additional time. Added handling for when ViewControllers are deallocated before the 10 seconds timeout
E2E tests
=> Fixed issue where ViewControllers were kept in memory for up to 10 seconds after being dismissed

CHANGELOG.md, Sources/BugsnagPerformance/Private/SystemInfoSampler.h, Sources/BugsnagPerformance/Private/SystemInfoSampler.mm
Thread Sanitizer detects a potential data race between Sampler thread and the main thread in `SystemInfoSampler.config` method
Added a mutex that helps synchronise Sampler thread and main thread when they access SystemInfoSampler properties
Manual testing
=> Fixed a potential data race warning in SystemInfoSampler

CHANGELOG.md, Sources/BugsnagPerformance/Private/BugsnagPerformanceSpan+Private.h, Sources/BugsnagPerformance/Private/Sampler.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm, Tests/BugsnagPerformanceTests/BatchTests.mm, Tests/BugsnagPerformanceTests/CrossTalkTests.mm, Tests/BugsnagPerformanceTests/OtlpTraceEncodingTests.mm, Tests/BugsnagPerformanceTests/SamplerTests.mm, Tests/BugsnagPerformanceTests/SpanOptionsTests.mm, Tests/BugsnagPerformanceTests/SpanStackingHandlerTests.mm, Tests/BugsnagPerformanceTests/SpanTests.mm, Tests/BugsnagPerformanceTests/TracerTests.mm, Tests/BugsnagPerformanceTests/WeakSpansListTests.mm
Setting sampling probability to 0.0 prevents all spans form being sent
Currently `samplingProbability` of a Span is `1.0` by default and it's only updated when the Span is closed.
It should be set to the current Sampler `samplingProbability`, then updated twice: when the Span is ended and when it's in a batch where spans are being selected to be sent out.
Also, setting `samplingProbability` to 0.0 should ensure that no spans are being sent.
- Added `samplingProbability` to `BugsnagPerformanceSpan` private constructor
- Added updating `samplingProbability` to `Sampler.sampled` for spans that pass the sampling
- Removed redundant `samplingProbability` updates on Spans
- Added an explicit check for `samplingProbability` 0.0 in `Sampler.sampled`
Unit tests
=> Fixed bugsnag.sampling.p attribute reporting to accurately reflect current sample rate

BugsnagPerformance.xcodeproj/project.pbxproj, CHANGELOG.md, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceSpanContext+Private.h, Sources/BugsnagPerformance/Private/NetworkHeaderInjector.mm, Sources/BugsnagPerformance/Private/Sampler.h, Sources/BugsnagPerformance/Public/BugsnagPerformance.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceRemoteSpanContext.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpanContext.mm, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformance.h, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceRemoteSpanContext.h, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanContext.h, Tests/BugsnagPerformanceTests/BugsnagPerformanceRemoteSpanContextTests.m, Tests/BugsnagPerformanceTests/BugsnagPerformanceSpanTests.mm, features/default/manual_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/FixtureXcFramework.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/ManualSpanWithRemoteContextParentScenario.swift
Allow easy cross-layer span parenting so that spans can be nested under spans from remote servers or non-native app layers (such as JavaScript in a WebView).
Introduced the new `BugsnagPerformanceRemoteSpanContext` class that encapsulates encoding & parsing of `BugsnagPerformanceSpanContexts` in the `traceparent` header format. The encoding can be applied to any `BugsnagPerformanceSpanContext` object, and the strings can be parsed into `BugsnagPerformanceRemoteSpanContext` objects.
Unit tests and E2E tests
=> Allow easy cross-layer span parenting

BugsnagPerformance.xcodeproj/project.pbxproj, Sources/BugsnagPerformance/Private/BSGPrioritizedStore.h, Sources/BugsnagPerformance/Private/BSGPrioritizedStore.m, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformancePriority+Private.h, Sources/BugsnagPerformance/Private/BugsnagPerformancePriority+Private.m, Sources/BugsnagPerformance/Private/SpanControl/BSGCompositeSpanControlProvider.h, Sources/BugsnagPerformance/Private/SpanControl/BSGCompositeSpanControlProvider.m, Sources/BugsnagPerformance/Public/BugsnagPerformance.mm, Sources/BugsnagPerformance/Public/BugsnagPerformancePriority.m, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpanQuery.m, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformance.h, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformancePriority.h, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanControl.h, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanControlProvider.h, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanQuery.h, Tests/BugsnagPerformanceTests/BSGCompositeSpanControlProviderTests.m, Tests/BugsnagPerformanceTests/BSGPrioritizedStoreTests.m
Offer a centralized interface for abstract span access where the `BugsnagPerformanceSpan` objects may not be directly reachable.
Introduced `BugsnagPerformanceSpanQuery` and `BugsnagPerformanceSpanControlProvider` that can be implemented to fulfil various types of span access.
Implemented a `BSGCompositeSpanControlProvider` that keeps a prioritized list of `BugsnagPerformanceSpanControlProvider`s and queries each of them in order, offering an easy single point of access to several providers at once.
Added the `+[BugsnagPerformance getSpanControlsWithQuery:]` function to allow centralised access to any known `BugsnagPerformanceSpanControlProviders`, avoiding the need to directly reference any single `BugsnagPerformanceSpanControlProvider`. `BugsnagPerformanceSpanControlProvider` objects …
=> Introduced SpanAccessProviders

CHANGELOG.md, Sources/BugsnagPerformance/Public/BugsnagPerformanceConfiguration.mm, Tests/BugsnagPerformanceTests/BugsnagPerformanceConfigurationTests.mm
Set default endpoints based on API key. If no custom endpoint is configured, payloads should be sent to `*.insighthub.smartbear.com` if the API key starts with `00000`.
Added unit tests
=> Set default endpoints based on API key

CHANGELOG.md, Sources/BugsnagPerformance/Private/BSGPSystemInfo.h, Sources/BugsnagPerformance/Private/BSGPSystemInfo.mm, Sources/BugsnagPerformance/Private/SystemInfoSampler.mm, features/default/metrics.feature, features/fixtures/ios/Scenarios/CPUMetricsScenario.swift
Total CPU usage values are expected to be in the range from 0 to 100.
Total CPU usage is now divided by the number of active cores
E2E tests
=> Fixed issue where reported total CPU usage values were not normalized

CHANGELOG.md, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.mm, Sources/BugsnagPerformance/Private/SpanAttributesProvider.h, Sources/BugsnagPerformance/Private/SpanAttributesProvider.mm, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, Tests/BugsnagPerformanceTests/SpanAttributesTests.mm, Tests/BugsnagPerformanceTests/TracerTests.mm, features/default/automatic_spans.feature
Network spans for tasks that throw an exception on attempt to read current/original request were categorized as custom and the error message was not added to them.
Additionally, network spans wouldn't land under Network tab by default.
- Added the necessary attributes to all network spans
- Added error message to spans created for tasks with non-obtainable request
Unit tests and E2E tests
=> Fixed issue where some Network spans were categorized as custom

Sources/BugsnagPerformance/Private/SpanAttributesProvider.mm, Tests/BugsnagPerformanceTests/SpanAttributesTests.mm
We shouldn’t send CPU metrics if there is no cpu_mean_total due to it being unavailable on the device.
If `processSampleCount` is zero that means that `cpu_mean_total` cannot be calculated.
So we check for it early and don't calculate any other cpu related attribute.
Added new unit tests with `cpu_mean_total` being unavailable.
Adjusted existing tests that checked main thread only and overhead only.
=> Don't send CPU data if cpu_mean_total is not available

CHANGELOG.md, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, Sources/BugsnagPerformance/Private/SpanAttributesProvider.h, Sources/BugsnagPerformance/Private/SpanAttributesProvider.mm, Tests/BugsnagPerformanceTests/SpanAttributesTests.mm, features/default/automatic_spans.feature
iOS pre-loads applications that it predicts will probably be used in near future. At that time the app is not visible on the screen. From phone users perspective it makes it feel like the application is starting up faster. The time elapsed from the pre-load to the time the app is open can be substantial.
Initially we decided to implement a heuristic to detect a pre-load (a long delay between the view controller being loaded and it started being presented), once we detect it then we add “(pre-loaded)” to the name of the Span and adjust its start time.
Now we are changing the approach and splitting those ViewLoads into two spans.
As the information on time elapsed between the end of viewLoad phase and the beginning of viewWillAppear phase isn’t relevant to application performance, we split …
=> Split Preload and Presentation phases of pre-loaded ViewLoads

CHANGELOG.md, Sources/BugsnagPerformance/Private/Tracer.mm, features/default/manual_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/FixtureXcFramework.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/SpanConditionsBlockedSpanScenario.swift
Calling block on spans that have ended but still haven't been processed due to being blocked should result with creating a new condition
E2E test
=> Fixed an issue preventing spans that have ended but are still blocked to be blocked with another condition
