Gemfile, Gemfile.lock, Sources/BugsnagPerformance/Private/BSGInternalConfig.c, Sources/BugsnagPerformance/Private/BSGInternalConfig.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/Worker.h, Sources/BugsnagPerformance/Private/Worker.mm, Tests/BugsnagPerformanceTests/WorkerTests.mm, features/fixtures/ios/Scenarios/BatchingWithTimeoutScenario.swift
The code for the 30s batch drain got broken in a way that also broke the e2e test that checked for it.
=> [PLAT-9796] Fix broken span batch drain timing code

README.md
=> Update README.md to fix integration guide link

.github/ISSUE_TEMPLATE/A.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/support.md
Adding auto generated templates for issues. 
Generated using support-issue-template-builder tool with these config updates: https://github.com/bugsnag/support-issue-template-builder/pull/16 
Adding several files to .github and ISSUE_TEMPLATE directories. 
Dry run used before main files generated: https://github.com/bugsnag/support-issue-template-builder#dry-run
=> Automated adjustment of repository templates

BugsnagPerformance.xcodeproj/project.pbxproj, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceSpan+Private.h, Sources/BugsnagPerformance/Private/IdGenerator.h, Sources/BugsnagPerformance/Private/OtlpTraceEncoding.mm, Sources/BugsnagPerformance/Private/SpanContextStack.h, Sources/BugsnagPerformance/Private/SpanContextStack.mm, Sources/BugsnagPerformance/Private/SpanData.h, Sources/BugsnagPerformance/Private/SpanData.mm, Sources/BugsnagPerformance/Private/SpanOptions.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpanOptions.m, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanContext.h, Tests/BugsnagPerformanceTests/BatchTests.mm, Tests/BugsnagPerformanceTests/OtlpTraceEncodingTests.mm, Tests/BugsnagPerformanceTests/SamplerTests.mm, Tests/BugsnagPerformanceTests/SpanContextStackTests.mm, Tests/BugsnagPerformanceTests/SpanOptionsTests.mm, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/ParentSpanScenario.swift, features/manual_spans.feature
Merges the following PRs from `integration/nested-spans` down to next:
* https://github.com/bugsnag/bugsnag-cocoa-performance/pull/48
* https://github.com/bugsnag/bugsnag-cocoa-performance/pull/49
These merged relatively clean. The final one will be messy, and done in a separate PR.
=> Integration merge 1

BugsnagPerformance.podspec.json, BugsnagPerformance.xcodeproj/project.pbxproj, CHANGELOG.md, Package.swift, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/SpanAttributesProvider.h, Sources/BugsnagPerformance/Private/SpanAttributesProvider.mm, Sources/BugsnagPerformance/Private/Tracer.h, Sources/BugsnagPerformance/Private/Tracer.mm, features/automatic_spans.feature, features/steps/app_steps.rb
Added network subtype attribute
=> [PLAT-9960] Add network subtype

CHANGELOG.md, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm
Applies #134 (for CI purposes)
=> Fix viewWillDisappear swizzle

CHANGELOG.md, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/SpanOptions.h, Sources/BugsnagPerformance/Private/Tracer.mm, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpanOptions.m, Sources/BugsnagPerformance/include/BugsnagPerformance/BugsnagPerformanceSpanOptions.h, Tests/BugsnagPerformanceTests/SpanOptionsTests.mm, Tests/BugsnagPerformanceTests/SpanTests.mm
Previous renaming missed some parts.
=> Finish renaming makeContextCurrent to makeCurrentContext

Sources/BugsnagPerformance/Private/OtlpUploader.mm, features/automatic_spans.feature, features/initial-p-value.feature, features/manual_spans.feature, features/sampling.feature, features/triggers.feature
Add `Bugsnag-Sent-At` header to all payloads to meet new requirements.
Updated all e2e tests to check this header.
=> [PLAT-10077] Add Bugsnag-Sent-At header to all payloads

README.md
=> docs(readme): add branding

Gemfile, Gemfile.lock, docker-compose.yml, features/manual_spans.feature
Upgrade to Maze Runner v8.
Covered by CI.
=> Upgrade to Maze Runner v8

.buildkite/pipeline.yml, Gemfile, Gemfile.lock, docker-compose.yml
Upload the `maze_output.zip` file for failed tests
Covered by CI
=> [PLAT-10738] Upload maze_output.zip for failed tests

.buildkite/pipeline.yml
Add e2e tests on iOS 17.
Covered by CI.
=> Add e2e tests on iOS 17

features/default/automatic_spans.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/AutoInstrumentPreLoadedViewLoadScenario.swift
Added a test for pre-loaded views. The scenario causes the view the load and then waits for 1.5 second before showing it.
E2E tests
=> Added an E2E test for pre-loaded views instrumentation

Gemfile
Add cocopods and xcpretty to the `gemfile` as it is missing. 
Covered by CI
=> [PLAT-11248] Add cocoapods and xcpretty to gemfile

.buildkite/pipeline.yml
Add bundle install to relevant steps within the CI to ensure gems are installed
Covered by CI
=> Add bundle install to relevant pipeline steps

Makefile, scripts/build-xcframework.sh
This PR adds the ability to build the binary xcframework from the command line.
=> [PLAT-12250] Support building an all-architecture xcframework from the makefile

BugsnagPerformance.xcodeproj/project.pbxproj, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceLibrary.h, Sources/BugsnagPerformance/Private/BugsnagPerformanceLibrary.mm, Sources/BugsnagPerformance/Private/EarlyConfiguration.mm, Sources/BugsnagPerformance/Private/Filesystem.h, Sources/BugsnagPerformance/Private/Filesystem.mm
Add more strategic logging to the library to aid in diagnosing issues in the field.
=> [PLAT-12393] Added more strategic debug and trace level logging

Sources/BugsnagPerformance/Private/OtlpTraceEncoding.h, Sources/BugsnagPerformance/Private/OtlpTraceEncoding.mm, features/default/manual_spans.feature, features/fixtures/ios/Scenarios/SetAttributesScenario.swift, features/steps/app_steps.rb
Allow arrays of primitives as attributes.
Added e2e tests.
=> [PLAT-12450] Allow array attributes

BugsnagPerformance.xcodeproj/project.pbxproj, Sources/BugsnagPerformance/Private/BugsnagPerformanceImpl.mm, Sources/BugsnagPerformance/Private/BugsnagPerformanceLibrary.mm, Sources/BugsnagPerformance/Private/Instrumentation/AppStartupInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation.mm, Sources/BugsnagPerformance/Private/Instrumentation/NetworkInstrumentation/BSGURLSessionPerformanceProxy.mm, Sources/BugsnagPerformance/Private/Instrumentation/ViewLoadInstrumentation.mm, Sources/BugsnagPerformance/Private/Span.h, Sources/BugsnagPerformance/Private/Utils.h, Sources/BugsnagPerformance/Public/BugsnagPerformanceSpan.mm
Add more standard (optional) logging to help in debugging.
=> More (optional) internal logging

features/fixtures/ios/Fixture/Fixture.swift, features/fixtures/ios/Fixture/ViewController.swift
Allows running the e2e fixture locally with a preset scenario.
=> Preset fixture support for local e2e debugging

BugsnagPerformanceSwift.podspec.json, CHANGELOG.md, Makefile
Changes Makefile to push BugsnagPerformanceSwift instead of BugsnagPerformanceSwiftUI
=> [PLAT-12662] deprecated BugsnagPerformanceSwiftUI podspec was being updated and pushed instead of BugsnagPerformanceSwift podspec

features/default/00_infrastructure_check.feature, features/fixtures/ios/Fixture.xcodeproj/project.pbxproj, features/fixtures/ios/Scenarios/InfraCheckMinimalBugsnagScenario.swift, features/fixtures/ios/Scenarios/InfraCheckNoBugsnagScenario.swift, features/fixtures/ios/Scenarios/Scenario.swift
=> [PLAT-12666] Add initial infrastructure check scenarios

CODEOWNERS.md
Upgrade repository security scoring by adding a list of designated code owners
=> Added CODEOWNERS.md file

.buildkite/pipeline.yml
Add iOS 18 Tests to the pipeline
Covered by CI
=> [PLAT-12960] iOS 18 Tests

.buildkite/block.full.yml, .buildkite/pipeline.full.yml, .buildkite/pipeline.yml, .buildkite/pipeline_trigger.sh
Add a full CI  pipeline to the existing pipeline setup. 
Covered by CI
=> [PLAT-13018] CI Full Run

README.md, SECURITY.md
Adds a Security Policy and updated the Read Me with the OpenSSF badge.
=> docs: add security policy and openssf badge

.buildkite/pipeline.full.yml
Move the iOS 17 CI tests from BS to BB
Covered by CI
=> [PLAT-12855] Move iOS 17 tests to BB

.github/workflows/signing.yml
Adds a workflow to upload signatures for assets included in a release.
=> Add signing workflow for release assets

.github/dependabot.yml
Adds basic dependabot update job.
=> build: add dependabot version updates

.github/workflows/signing.yml
Restricts the permissions for the workflow token
=> Restrict built-in github token

.github/workflows/pull_request.yml, .github/workflows/scorecard.yml
Rolls up #354,  #355 and #356 for merging.
=> Rollup GitHub Action updates

CHANGELOG.md, Sources/BugsnagPerformance/Private/Tracer.mm, Tests/BugsnagPerformanceTests/TracerTests.mm, features/default/automatic_spans.feature, features/default/manual_spans.feature, features/default/network.feature
Network spans should be type CLIENT (3). Add code to ensure it is.
Added unit test.
=> [PLAT-11407] Network spans should be type CLIENT

CHANGELOG.md, Makefile
Added a missing entry to CHANGELOG.md and updated release step in Makefile to reflect the new workflow
=> Updated CHANGELOG.md and Makefile

Makefile
We need to keep MARKETING_VERSION in sync
=> Added updating MARKETING_VERSION to Makefile bump step

features/fixtures/ios/Fixture/Fixture.swift
Same thing as for https://github.com/bugsnag/bugsnag-cocoa/pull/1760
The e2e automation tools aren't able to copy from the Caches directory, so what we'll do now is on every fixture app launch, copy the Bugsnag-specific directories under the Caches dir to ~/Documents/BugsnagCachesCopy
=> Copy Bugsnag dirs from Caches into Documents in the e2e fixture

.buildkite/pipeline.full.yml, .buildkite/pipeline.yml
Add automatic retries to Appium steps for the exit code 103
Covered by CI
=> Add retries to Appium steps
